### ISSUE TITLE
Sensitive data

### ISSUE THREAD

**Issue by Ferrozo** [aldairandre/docker-help#1]
Hide your sensitive data

**Comment by aldairandre** [comment]
what sensitive data?

**Comment by aldairandre** [comment]
what sensitive data?
if you are talking about `MONGO_INITDB_ROOT_USER=admin -e MONGO_INITDB_PASSWORD=123` , this is just an example! 
But I'm reading the documentation now to know how to use Env

**Comment by Ferrozo** [comment]
Yes it was about user info.
Okay I got it, but always better to prevent :)
